sudo: required
services: 
  - docker

before_install:
  - docker build -t ajax/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ajax/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "elasticbean-docker-node-web"
  env: "elasticbean-docker-node-web-env"
  bucket_name: "elasticbeanstalk-us-east-1-923276396145"
  bucket_path: "elasticbean-docker-node-web"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

  

